### ISSUE TITLE
504 GATEWAY_TIMEOUT fails instead of wait and retry:

### ISSUE THREAD

**Issue by grebois** [smarkets/marge-bot#144]
```
2018-10-16 11:44:35,889 DEBUG Starting new HTTPS connection *********
2018-10-16 11:45:35,259 DEBUG *********
2018-10-16 11:45:35,263 DEBUG RESPONSE CODE: 504
2018-10-16 11:45:35,269 DEBUG RESPONSE BODY: b''
Traceback (most recent call last):
  File "/nix/store/77wrcwqx8p2wbw3n0v5v4lsvh7bwn01w-python3.6-marge-0.7.0/bin/.marge.app-wrapped", line 4, in <module>
    marge.app.main()
  File "/nix/store/77wrcwqx8p2wbw3n0v5v4lsvh7bwn01w-python3.6-marge-0.7.0/lib/python3.6/site-packages/marge/app.py", line 261, in main
    marge_bot.start()
  File "/nix/store/77wrcwqx8p2wbw3n0v5v4lsvh7bwn01w-python3.6-marge-0.7.0/lib/python3.6/site-packages/marge/bot.py", line 41, in start
    self._run(repo_manager)
  File "/nix/store/77wrcwqx8p2wbw3n0v5v4lsvh7bwn01w-python3.6-marge-0.7.0/lib/python3.6/site-packages/marge/bot.py", line 55, in _run
    projects = self._get_projects()
  File "/nix/store/77wrcwqx8p2wbw3n0v5v4lsvh7bwn01w-python3.6-marge-0.7.0/lib/python3.6/site-packages/marge/bot.py", line 69, in _get_projects
    my_projects = Project.fetch_all_mine(self._api)
  File "/nix/store/77wrcwqx8p2wbw3n0v5v4lsvh7bwn01w-python3.6-marge-0.7.0/lib/python3.6/site-packages/marge/project.py", line 32, in fetch_all_mine
    {'membership': True, 'with_merge_requests_enabled': True},
  File "/nix/store/77wrcwqx8p2wbw3n0v5v4lsvh7bwn01w-python3.6-marge-0.7.0/lib/python3.6/site-packages/marge/gitlab.py", line 61, in collect_all_pages
    page = self.call(get_command.for_page(page_no))
  File "/nix/store/77wrcwqx8p2wbw3n0v5v4lsvh7bwn01w-python3.6-marge-0.7.0/lib/python3.6/site-packages/marge/gitlab.py", line 55, in call
    raise error(response.status_code, err_message)
marge.gitlab.InternalServerError: (504, 'GATEWAY_TIMEOUT')
```

**Comment by valentindavid** [comment]
Same with 502 (Bad Gateway).
