### ISSUE TITLE
Failure giving useful input when branch rebased while Marge trying to merge

### ISSUE THREAD

**Issue by nanonyme** [smarkets/marge-bot#148]
https://gitlab.com/freedesktop-sdk/freedesktop-sdk/merge_requests/633

2018-10-31 15:54:06,286 INFO Ensuring MR !633 is mergeable
2018-10-31 15:54:07,700 ERROR Unanticipated ApiError from GitLab on merge attempt
Traceback (most recent call last):
  File "/nix/store/mpigf8qvjjsnnsqk8q5iam5hdpqxh8s8-python3.6-marge-0.8.0/lib/python3.6/site-packages/marge/single_merge_job.py", line 75, in update_merge_request_and_accept
    merge_request.accept(remove_branch=True, sha=actual_sha)
  File "/nix/store/mpigf8qvjjsnnsqk8q5iam5hdpqxh8s8-python3.6-marge-0.8.0/lib/python3.6/site-packages/marge/merge_request.py", line 125, in accept
    sha=sha or self.sha,  # if provided, ensures what is merged is what we want (or fails)
  File "/nix/store/mpigf8qvjjsnnsqk8q5iam5hdpqxh8s8-python3.6-marge-0.8.0/lib/python3.6/site-packages/marge/gitlab.py", line 55, in call
    raise error(response.status_code, err_message)
marge.gitlab.Conflict: (409, {'message': 'SHA does not match HEAD of source branch: f1c318c21746a4bd3c26574d82e8cc1c88394d9b'})
2018-10-31 15:54:07,703 WARNING I couldn't merge this branch: had some issue with GitLab, check my logs...

The comment that Marge gave didn't make it at all obvious what went wrong, there also shouldn't be a stack trace when this happens

**Comment by GMartinez-Sisti** [comment]
I'm having the same issue with:
- Marge-bot: 0.9.1
- Gitlab: 12.2.3-ee (3a1dd80d30c)

The difference is that the rebase and merge are successfully performed, but Margebot still posts:
> I couldn't merge this branch: had some issue with GitLab, check my logs...

And in the logs we have (redacted):
```
2019-09-23 13:24:02,498 INFO Got 1 requests to merge;
2019-09-23 13:24:02,498 INFO Attempting to merge the oldest MR...
2019-09-23 13:24:02,498 INFO Processing !9999 - 'Description'
2019-09-23 13:24:03,880 INFO Ensuring MR !9999 is mergeable
2019-09-23 13:24:04,171 INFO Running git -C /tmp4ackfybf/tmphr1ovtvd fetch --prune origin
2019-09-23 13:24:06,582 INFO Running git -C /tmp4ackfybf/tmphr1ovtvd checkout -B branch-name origin/branch-name --
2019-09-23 13:24:06,879 INFO Running git -C /tmp4ackfybf/tmphr1ovtvd rebase origin/master
2019-09-23 13:24:08,085 INFO Running git -C /tmp4ackfybf/tmphr1ovtvd rev-parse HEAD
2019-09-23 13:24:08,168 INFO Running git -C /tmp4ackfybf/tmphr1ovtvd rev-parse origin/master
2019-09-23 13:24:08,174 INFO Adding trailers for MR !9999
2019-09-23 13:24:08,175 INFO Running git -C /tmp4ackfybf/tmphr1ovtvd checkout branch-name --
2019-09-23 13:24:08,389 INFO Running git -C /tmp4ackfybf/tmphr1ovtvd diff-index --quiet HEAD
2019-09-23 13:24:08,480 INFO Running git -C /tmp4ackfybf/tmphr1ovtvd ls-files --others
2019-09-23 13:24:08,583 INFO Running git -C /tmp4ackfybf/tmphr1ovtvd push --force origin branch-name:branch-name
2019-09-23 13:24:16,482 INFO Running git -C /tmp4ackfybf/tmphr1ovtvd checkout -B master --
2019-09-23 13:24:16,668 INFO Running git -C /tmp4ackfybf/tmphr1ovtvd branch -D branch-name
2019-09-23 13:24:16,674 INFO Commit id to merge '10a1d003a0353afdf728fd0f04e82505813e8cff' (into: '379d60f8c570820c5f94059dfb848c64293da215')
2019-09-23 13:24:21,818 INFO Waiting for CI to pass for MR !9999
2019-09-23 13:24:21,927 WARNING No pipeline listed for 10a1d003a0353afdf728fd0f04e82505813e8cff on branch branch-name
2019-09-23 13:24:21,927 WARNING Suspicious CI status: None
2019-09-23 13:34:35,074 INFO CI for MR !9999 passed
2019-09-23 13:34:37,239 INFO Ensuring MR !9999 is mergeable
2019-09-23 13:34:39,146 ERROR Unanticipated ApiError from GitLab on merge attempt
Traceback (most recent call last):
  File "/nix/store/ji6cn8jmazcy95rm693n15dcx00baqqc-python3.6-marge-0.9.1/lib/python3.6/site-packages/marge/single_merge_job.py", line 83, in update_merge_request_and_accept
    merge_request.accept(remove_branch=True, sha=actual_sha)
  File "/nix/store/ji6cn8jmazcy95rm693n15dcx00baqqc-python3.6-marge-0.9.1/lib/python3.6/site-packages/marge/merge_request.py", line 163, in accept
    sha=sha or self.sha,  # if provided, ensures what is merged is what we want (or fails)
  File "/nix/store/ji6cn8jmazcy95rm693n15dcx00baqqc-python3.6-marge-0.9.1/lib/python3.6/site-packages/marge/gitlab.py", line 65, in call
    raise error(response.status_code, err_message)
marge.gitlab.InternalServerError: (500, {'message': '500 Internal Server Error'})
2019-09-23 13:34:39,146 WARNING I couldn't merge this branch: had some issue with GitLab, check my logs...
2019-09-23 13:34:39,146 INFO Unassigning from MR !9999
```
