### ISSUE TITLE
Unhandled exception when checking the CI status of a fork branch

### ISSUE THREAD

**Issue by alatiera** [smarkets/marge-bot#217]
The target project is usinga rebase only workflow, with 'only accept on green ci' option enabled. We're using the `0.9.0` docker image.

The MR link is the following:

https://gitlab.freedesktop.org/gstreamer/gst-ci/merge_requests/147

```
2019-07-16 08:11:22,398 INFO Got 1 requests to merge;
2019-07-16 08:11:22,399 INFO Attempting to merge the oldest MR...
2019-07-16 08:11:22,399 INFO Processing !147 - 'docker/fedora: avoid hardcoding the fedora version in the setup script'
2019-07-16 08:11:23,503 INFO Ensuring MR !147 is mergeable
2019-07-16 08:11:24,490 INFO Running git -C /tmp_cjpmw6y/tmpdba26nv0 remote rm source
2019-07-16 08:11:24,497 WARNING git returned 128
2019-07-16 08:11:24,497 WARNING stdout: b''
2019-07-16 08:11:24,501 WARNING stderr: b"fatal: No such remote: 'source'\n"
2019-07-16 08:11:24,501 INFO Running git -C /tmp_cjpmw6y/tmpdba26nv0 remote add source git@gitlab.freedesktop.org:alatiera/gst-ci.git
2019-07-16 08:11:24,508 INFO Running git -C /tmp_cjpmw6y/tmpdba26nv0 fetch --prune source
2019-07-16 08:11:27,096 INFO Running git -C /tmp_cjpmw6y/tmpdba26nv0 fetch --prune origin
2019-07-16 08:11:29,958 INFO Running git -C /tmp_cjpmw6y/tmpdba26nv0 remote rm source
2019-07-16 08:11:29,986 INFO Running git -C /tmp_cjpmw6y/tmpdba26nv0 remote add source git@gitlab.freedesktop.org:alatiera/gst-ci.git
2019-07-16 08:11:29,994 INFO Running git -C /tmp_cjpmw6y/tmpdba26nv0 fetch --prune source
2019-07-16 08:11:32,113 INFO Running git -C /tmp_cjpmw6y/tmpdba26nv0 checkout -B alatiera/fedora-docker-minor source/alatiera/fedora-docker-minor --
2019-07-16 08:11:32,123 INFO Running git -C /tmp_cjpmw6y/tmpdba26nv0 rebase origin/master
2019-07-16 08:11:32,432 INFO Running git -C /tmp_cjpmw6y/tmpdba26nv0 rev-parse HEAD
2019-07-16 08:11:32,445 INFO Running git -C /tmp_cjpmw6y/tmpdba26nv0 rev-parse origin/master
2019-07-16 08:11:32,452 INFO Adding trailers for MR !147
2019-07-16 08:11:32,453 INFO Running git -C /tmp_cjpmw6y/tmpdba26nv0 checkout alatiera/fedora-docker-minor --
2019-07-16 08:11:32,469 INFO Running git -C /tmp_cjpmw6y/tmpdba26nv0 diff-index --quiet HEAD
2019-07-16 08:11:32,478 INFO Running git -C /tmp_cjpmw6y/tmpdba26nv0 ls-files --others
2019-07-16 08:11:32,490 INFO Running git -C /tmp_cjpmw6y/tmpdba26nv0 config --get remote.source.url
2019-07-16 08:11:32,497 INFO Running git -C /tmp_cjpmw6y/tmpdba26nv0 push --force source alatiera/fedora-docker-minor:alatiera/fedora-docker-minor
2019-07-16 08:11:34,777 INFO Running git -C /tmp_cjpmw6y/tmpdba26nv0 checkout -B master --
2019-07-16 08:11:34,786 INFO Running git -C /tmp_cjpmw6y/tmpdba26nv0 branch -D alatiera/fedora-docker-minor
2019-07-16 08:11:34,797 INFO Commit id to merge '7e88d99f9504dfdda7fa8a31e75f560c285cda3a' (into: 'a110f8399e1dedc70ea1c4093afc9be218a5ea9c')
2019-07-16 08:11:40,434 INFO Waiting for CI to pass for MR !147
2019-07-16 08:11:41,385 ERROR Unexpected Exception
Traceback (most recent call last):
  File "/nix/store/86sgn6i8y2qdph3r0lfdhbdayj5jfn35-python3.6-marge-0.9.0/lib/python3.6/site-packages/marge/single_merge_job.py", line 24, in execute
    self.update_merge_request_and_accept(approvals)
  File "/nix/store/86sgn6i8y2qdph3r0lfdhbdayj5jfn35-python3.6-marge-0.9.0/lib/python3.6/site-packages/marge/single_merge_job.py", line 76, in update_merge_request_and_accept
    self.wait_for_ci_to_pass(merge_request, actual_sha)
  File "/nix/store/86sgn6i8y2qdph3r0lfdhbdayj5jfn35-python3.6-marge-0.9.0/lib/python3.6/site-packages/marge/job.py", line 170, in wait_for_ci_to_pass
    ci_status = self.get_mr_ci_status(merge_request, commit_sha=commit_sha)
  File "/nix/store/86sgn6i8y2qdph3r0lfdhbdayj5jfn35-python3.6-marge-0.9.0/lib/python3.6/site-packages/marge/job.py", line 143, in get_mr_ci_status
    self._api,
  File "/nix/store/86sgn6i8y2qdph3r0lfdhbdayj5jfn35-python3.6-marge-0.9.0/lib/python3.6/site-packages/marge/pipeline.py", line 39, in pipelines_by_merge_request
    project_id=project_id, merge_request_iid=merge_request_iid,
  File "/nix/store/86sgn6i8y2qdph3r0lfdhbdayj5jfn35-python3.6-marge-0.9.0/lib/python3.6/site-packages/marge/gitlab.py", line 65, in call
    raise error(response.status_code, err_message)
marge.gitlab.NotFound: (404, {'message': '404 Not found'})
2019-07-16 08:11:42,614 INFO Unassigning from MR !147
Traceback (most recent call last):
  File "/nix/store/86sgn6i8y2qdph3r0lfdhbdayj5jfn35-python3.6-marge-0.9.0/bin/.marge.app-wrapped", line 4, in <module>
    marge.app.main()
  File "/nix/store/86sgn6i8y2qdph3r0lfdhbdayj5jfn35-python3.6-marge-0.9.0/lib/python3.6/site-packages/marge/app.py", line 314, in main
    marge_bot.start()
  File "/nix/store/86sgn6i8y2qdph3r0lfdhbdayj5jfn35-python3.6-marge-0.9.0/lib/python3.6/site-packages/marge/bot.py", line 42, in start
    self._run(repo_manager)
  File "/nix/store/86sgn6i8y2qdph3r0lfdhbdayj5jfn35-python3.6-marge-0.9.0/lib/python3.6/site-packages/marge/bot.py", line 60, in _run
    projects,
  File "/nix/store/86sgn6i8y2qdph3r0lfdhbdayj5jfn35-python3.6-marge-0.9.0/lib/python3.6/site-packages/marge/bot.py", line 98, in _process_projects
    self._process_merge_requests(repo_manager, project, merge_requests)
  File "/nix/store/86sgn6i8y2qdph3r0lfdhbdayj5jfn35-python3.6-marge-0.9.0/lib/python3.6/site-packages/marge/bot.py", line 175, in _process_merge_requests
    merge_job.execute()
  File "/nix/store/86sgn6i8y2qdph3r0lfdhbdayj5jfn35-python3.6-marge-0.9.0/lib/python3.6/site-packages/marge/single_merge_job.py", line 24, in execute
    self.update_merge_request_and_accept(approvals)
  File "/nix/store/86sgn6i8y2qdph3r0lfdhbdayj5jfn35-python3.6-marge-0.9.0/lib/python3.6/site-packages/marge/single_merge_job.py", line 76, in update_merge_request_and_accept
    self.wait_for_ci_to_pass(merge_request, actual_sha)
  File "/nix/store/86sgn6i8y2qdph3r0lfdhbdayj5jfn35-python3.6-marge-0.9.0/lib/python3.6/site-packages/marge/job.py", line 170, in wait_for_ci_to_pass
    ci_status = self.get_mr_ci_status(merge_request, commit_sha=commit_sha)
  File "/nix/store/86sgn6i8y2qdph3r0lfdhbdayj5jfn35-python3.6-marge-0.9.0/lib/python3.6/site-packages/marge/job.py", line 143, in get_mr_ci_status
    self._api,
  File "/nix/store/86sgn6i8y2qdph3r0lfdhbdayj5jfn35-python3.6-marge-0.9.0/lib/python3.6/site-packages/marge/pipeline.py", line 39, in pipelines_by_merge_request
    project_id=project_id, merge_request_iid=merge_request_iid,
  File "/nix/store/86sgn6i8y2qdph3r0lfdhbdayj5jfn35-python3.6-marge-0.9.0/lib/python3.6/site-packages/marge/gitlab.py", line 65, in call
    raise error(response.status_code, err_message)
marge.gitlab.NotFound: (404, {'message': '404 Not found'})

```

**Comment by JaimeLennox** [comment]
Ah, I think this is because when fetching pipelines by merge request we fetch them for the source project - it should probably be the target project, given that's where the merge request exists.

**Comment by alatiera** [comment]
Thanks for the quick fix! Tested it and indeed it works!
