### ISSUE TITLE
404 on /api/v4/projects/<project-id>

### ISSUE THREAD

**Issue by jeehoonkang** [smarkets/marge-bot#285]
My marge bot fails with "I'm broken on the inside, please somebody fix me...", and its log says:

```
gitlab-marge-bot_1  | marge.gitlab.NotFound: (404, {'message': '404 Project Not Found'})                                                                       [160/1828]
gitlab-marge-bot_1  | 2021-01-30 07:00:57,054 INFO Unassigning from MR !20                                                                                               
gitlab-marge-bot_1  | Traceback (most recent call last):                                                                                                                 
gitlab-marge-bot_1  |   File "/nix/store/vn94z48nxysnirpx7pkqacygmkgr1q18-python3.6-marge-0.9.4/bin/.marge.app-wrapped", line 4, in <module>                             
gitlab-marge-bot_1  |     marge.app.main()                                                                                                                               
gitlab-marge-bot_1  |   File "/nix/store/vn94z48nxysnirpx7pkqacygmkgr1q18-python3.6-marge-0.9.4/lib/python3.6/site-packages/marge/app.py", line 333, in main             
gitlab-marge-bot_1  |     marge_bot.start()                                                                                                                              
gitlab-marge-bot_1  |   File "/nix/store/vn94z48nxysnirpx7pkqacygmkgr1q18-python3.6-marge-0.9.4/lib/python3.6/site-packages/marge/bot.py", line 42, in start             
gitlab-marge-bot_1  |     self._run(repo_manager)                                                                                                                        
gitlab-marge-bot_1  |   File "/nix/store/vn94z48nxysnirpx7pkqacygmkgr1q18-python3.6-marge-0.9.4/lib/python3.6/site-packages/marge/bot.py", line 60, in _run              
gitlab-marge-bot_1  |     projects,                                                                                                                                      
gitlab-marge-bot_1  |   File "/nix/store/vn94z48nxysnirpx7pkqacygmkgr1q18-python3.6-marge-0.9.4/lib/python3.6/site-packages/marge/bot.py", line 98, in _process_projects 
gitlab-marge-bot_1  |     self._process_merge_requests(repo_manager, project, merge_requests)                                                                            
gitlab-marge-bot_1  |   File "/nix/store/vn94z48nxysnirpx7pkqacygmkgr1q18-python3.6-marge-0.9.4/lib/python3.6/site-packages/marge/bot.py", line 175, in _process_merge_re
quests                                                                                                                                                                   
gitlab-marge-bot_1  |     merge_job.execute()                                                                                                                            
gitlab-marge-bot_1  |   File "/nix/store/vn94z48nxysnirpx7pkqacygmkgr1q18-python3.6-marge-0.9.4/lib/python3.6/site-packages/marge/single_merge_job.py", line 24, in execu
te                                                                                                                                                                       
gitlab-marge-bot_1  |     self.update_merge_request_and_accept(approvals)                                                                                                
gitlab-marge-bot_1  |   File "/nix/store/vn94z48nxysnirpx7pkqacygmkgr1q18-python3.6-marge-0.9.4/lib/python3.6/site-packages/marge/single_merge_job.py", line 50, in updat
e_merge_request_and_accept                                                                                                                                               
gitlab-marge-bot_1  |     source_project, source_repo_url, _ = self.fetch_source_project(merge_request)                                                                  
gitlab-marge-bot_1  |   File "/nix/store/vn94z48nxysnirpx7pkqacygmkgr1q18-python3.6-marge-0.9.4/lib/python3.6/site-packages/marge/job.py", line 227, in fetch_source_proj
ect                                                                                                                                                                      
gitlab-marge-bot_1  |     source_project = self.get_source_project(merge_request)                                                                                        
gitlab-marge-bot_1  |   File "/nix/store/vn94z48nxysnirpx7pkqacygmkgr1q18-python3.6-marge-0.9.4/lib/python3.6/site-packages/marge/job.py", line 242, in get_source_projec
t                                                                                                                                                                        
gitlab-marge-bot_1  |     api=self._api,                                                                                                                                 
gitlab-marge-bot_1  |   File "/nix/store/vn94z48nxysnirpx7pkqacygmkgr1q18-python3.6-marge-0.9.4/lib/python3.6/site-packages/marge/project.py", line 15, in fetch_by_id   
gitlab-marge-bot_1  |     info = api.call(GET('/projects/%s' % project_id))                                                                                              
gitlab-marge-bot_1  |   File "/nix/store/vn94z48nxysnirpx7pkqacygmkgr1q18-python3.6-marge-0.9.4/lib/python3.6/site-packages/marge/gitlab.py", line 65, in call           
gitlab-marge-bot_1  |     raise error(response.status_code, err_message)                                                                                                 
gitlab-marge-bot_1  | marge.gitlab.NotFound: (404, {'message': '404 Project Not Found'}) 
```

It's run inside a docker container, and I checked that `MARGE_AUTH_TOKEN` is set in environment, and the token is valid (`curl --header 'PRIVATE-TOKEN: <token>' <domain>/api/v4/projects/10` works and prints values in my local).

I wonder how I can proceed in debugging.  I'm using the latest `smarkets/marge-bot:latest` and `gitlab/gitlab-ce:latest` docker images.

Thanks!

**Comment by jcpetruzza** [comment]
check how to enable debug logging, you should then see the request that is getting the 404

**Comment by jeehoonkang** [comment]
Thanks! it was due to the fact that the marge bot requires permission for the forked project, while it didn't have it.
