### ISSUE TITLE
Enabling automerge on gitlab side during marge processing causes exceptional behavior

### ISSUE THREAD

**Issue by david-duncan** [smarkets/marge-bot#33]
Repro:

1) Assign marge
2) During marges processing enable automerge
3) Sometime later marge will error out: "I'm broken on the inside, please somebody fix me."

Everything worked but someone was impatient so marge complains

**Comment by jcpetruzza** [comment]
Interesting. Could you paste the fragment of the log from the time you get the error message?

**Comment by david-duncan** [comment]
2017-08-03 16:19:07,862 ERROR Unexpected Exception
Traceback (most recent call last):
  File "/nix/store/0yjvdhpw9cpmahw6ndfgby9n4pz8m79i-python3.6-marge-0.1.1/lib/python3.6/site-packages/marge/job.py", line 57, in execute
    self.rebase_and_accept(approvals)
  File "/nix/store/0yjvdhpw9cpmahw6ndfgby9n4pz8m79i-python3.6-marge-0.1.1/lib/python3.6/site-packages/marge/job.py", line 119, in rebase_and_accept
    sha_now = Commit.last_on_branch(source_project.id, merge_request.source_branch, api).id
  File "/nix/store/0yjvdhpw9cpmahw6ndfgby9n4pz8m79i-python3.6-marge-0.1.1/lib/python3.6/site-packages/marge/commit.py", line 26, in last_on_branch
    branch=branch,
  File "/nix/store/0yjvdhpw9cpmahw6ndfgby9n4pz8m79i-python3.6-marge-0.1.1/lib/python3.6/site-packages/marge/gitlab.py", line 55, in call
    raise error(response.status_code, err_message)

marge.gitlab.NotFound: (404, {'message': '404 Branch Not Found'})
Traceback (most recent call last):
  File "/nix/store/0yjvdhpw9cpmahw6ndfgby9n4pz8m79i-python3.6-marge-0.1.1/bin/.marge.app-wrapped", line 4, in <module>
    marge.app.main()
  File "/nix/store/0yjvdhpw9cpmahw6ndfgby9n4pz8m79i-python3.6-marge-0.1.1/lib/python3.6/site-packages/marge/app.py", line 114, in main
    marge_bot.start()
  File "/nix/store/0yjvdhpw9cpmahw6ndfgby9n4pz8m79i-python3.6-marge-0.1.1/lib/python3.6/site-packages/marge/bot.py", line 50, in start
    self._run(repo_manager)
  File "/nix/store/0yjvdhpw9cpmahw6ndfgby9n4pz8m79i-python3.6-marge-0.1.1/lib/python3.6/site-packages/marge/bot.py", line 92, in _run
    job.execute()
  File "/nix/store/0yjvdhpw9cpmahw6ndfgby9n4pz8m79i-python3.6-marge-0.1.1/lib/python3.6/site-packages/marge/job.py", line 57, in execute
    self.rebase_and_accept(approvals)
  File "/nix/store/0yjvdhpw9cpmahw6ndfgby9n4pz8m79i-python3.6-marge-0.1.1/lib/python3.6/site-packages/marge/job.py", line 119, in rebase_and_accept
    sha_now = Commit.last_on_branch(source_project.id, merge_request.source_branch, api).id
  File "/nix/store/0yjvdhpw9cpmahw6ndfgby9n4pz8m79i-python3.6-marge-0.1.1/lib/python3.6/site-packages/marge/commit.py", line 26, in last_on_branch
    branch=branch,
  File "/nix/store/0yjvdhpw9cpmahw6ndfgby9n4pz8m79i-python3.6-marge-0.1.1/lib/python3.6/site-packages/marge/gitlab.py", line 55, in call
    raise error(response.status_code, err_message)
marge.gitlab.NotFound: (404, {'message': '404 Branch Not Found'})

**Comment by jcpetruzza** [comment]
Ok, so I think what is happening is that if you hit "Merge when build succeeds" and the branch is marked for deletion, then by the time marge tries to merge it, the branch is gone and gitlab fails with a 404, on which we panic.

On 40x errors we should just check if the request is merged anyway and, if it was, call it a day.
