### ISSUE TITLE
Don't assume a branch called `master` exists when removing the merged branch

### ISSUE THREAD

**Issue by alexandear** [smarkets/marge-bot#88]
It does not always merge request should be merged into `master`. E.g., in some git workflows, MR should be merged into `develop` branch. I propose to add configuration parameter `--branch-name-merge-into <string name>` for such situations.

**Comment by jcpetruzza** [comment]
I don't think we are hard-coding `master` anywhere. You indicate the target branch on GitLab when you create the merge-request (which by default will be `master`). Will that work for you?

**Comment by alexandear** [comment]
Yes, there are two places where `master` is hardcoded:

```
.git.py

def remove_branch(self, branch):
    assert branch != 'master'
    self.git('checkout', 'master', '--')
    self.git('branch', '-D', branch)
```

```
job.py

if source_branch != 'master':
    repo.remove_branch(source_branch)
else:
    assert source_repo_url is not None
```

### How to reproduce

Create MR in GitLab. Target branch is not `master`, e.g. `3.10`.

![image](https://user-images.githubusercontent.com/3228886/36909419-91593488-1e46-11e8-9b66-2b0660be7d4e.png)

Then assign MR to Marge Bot.

### Expected result

Marge Bot merges source branch into target branch `3.10`.

### Current result

Exception occured:

```
2018-03-02 18:17:25,096 INFO Running git clone --origin=origin git@gitlab/MessagesTransceiver.git 'C:\Users\ADMINI~1\AppData\Local\Temp\tmp81lxjhwu\tmp59d9phm1'
2018-03-02 18:18:31,330 INFO Running git -C 'C:\Users\ADMINI~1\AppData\Local\Temp\tmp81lxjhwu\tmp59d9phm1' config user.email marge-bot@example.com
2018-03-02 18:18:31,957 INFO Running git -C 'C:\Users\ADMINI~1\AppData\Local\Temp\tmp81lxjhwu\tmp59d9phm1' config user.name 'Marge Bot'
2018-03-02 18:18:31,981 INFO Processing !8 - 'Remove using namespace'
2018-03-02 18:18:32,188 INFO Running git -C 'C:\Users\ADMINI~1\AppData\Local\Temp\tmp81lxjhwu\tmp59d9phm1' fetch --prune origin
2018-03-02 18:18:35,721 INFO Running git -C 'C:\Users\ADMINI~1\AppData\Local\Temp\tmp81lxjhwu\tmp59d9phm1' checkout -B refactor/removeUsingNamespace origin/refactor/removeUsingNamespace --
2018-03-02 18:18:35,892 INFO Running git -C 'C:\Users\ADMINI~1\AppData\Local\Temp\tmp81lxjhwu\tmp59d9phm1' rebase origin/3.10
2018-03-02 18:18:43,460 INFO Running git -C 'C:\Users\ADMINI~1\AppData\Local\Temp\tmp81lxjhwu\tmp59d9phm1' rev-parse HEAD
2018-03-02 18:18:43,568 INFO Running git -C 'C:\Users\ADMINI~1\AppData\Local\Temp\tmp81lxjhwu\tmp59d9phm1' checkout refactor/removeUsingNamespace --
2018-03-02 18:18:43,596 INFO Running git -C 'C:\Users\ADMINI~1\AppData\Local\Temp\tmp81lxjhwu\tmp59d9phm1' diff-index --quiet HEAD
2018-03-02 18:18:43,628 INFO Running git -C 'C:\Users\ADMINI~1\AppData\Local\Temp\tmp81lxjhwu\tmp59d9phm1' ls-files --others
2018-03-02 18:18:43,740 INFO Running git -C 'C:\Users\ADMINI~1\AppData\Local\Temp\tmp81lxjhwu\tmp59d9phm1' push --force origin refactor/removeUsingNamespace
2018-03-02 18:18:45,010 INFO Running git -C 'C:\Users\ADMINI~1\AppData\Local\Temp\tmp81lxjhwu\tmp59d9phm1' rev-parse origin/3.10
2018-03-02 18:18:45,032 INFO Running git -C 'C:\Users\ADMINI~1\AppData\Local\Temp\tmp81lxjhwu\tmp59d9phm1' checkout master --
2018-03-02 18:18:45,071 WARNING git returned 128
2018-03-02 18:18:45,071 WARNING stdout: b''
2018-03-02 18:18:45,071 WARNING stderr: b'fatal: invalid reference: master\n'
2018-03-02 18:18:45,071 ERROR Unexpected Git error
Traceback (most recent call last):
  File "C:\marge-bot\marge\git.py", line 163, in git
    return _run(*command, env=env, check=True, timeout=timeout_seconds)
  File "C:\marge-bot\marge\git.py", line 189, in _run
    retcode, process.args, output=stdout, stderr=stderr,
subprocess.CalledProcessError: Command '('git', '-C', 'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp
```

**Comment by jcpetruzza** [comment]
Oh, I see. Marge is actually trying to merge onto your `3.10` branch. It is when cleaning up that we try to remove the source branch from the local repo and for that we need to first checkout something else and for that we assume a branched called `master` to exist.
